#page title
page_title                                : Yacuber | Seguridad y Rapidez                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : bo                                        #quired outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=app.dvgeo.yacuber.passenger                                          # Enter Google Play Store URL.
presskit_download_link                    : https://conductor.yacuber.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : https://raw.githubusercontent.com/nienna6/yacuber/master/assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Yacuber                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Viaja Seguro.                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : • Registrate </br> • Pide un taxi </br> • Viaja seguro

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nienna Online                                
your_link                                 : https://niennaonline.com                     
your_city                                 : yacuiba                                
email_address                             : contacto@yacuber.com
facebook_username                         : yacuber                                          
instagram_username                        : yacuber
twitter_username                          : yacuber
github_username                           : 
youtube_username                          : yacuber
mastodon_link                             : https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Seguridad
    description                           : Viajes geolocalizados, conductores identificados y un botón de seguridad para cuidarte.
    fontawesome_icon_name                 : map
    
  - title                                 : Rapidez
    description                           : Asegurate que siempre tendras el taxi mas cercano a ti, para que no tengas que esperar.
    fontawesome_icon_name                 : bolt

  - title                                 : El mejor precio
    description                           : Acepta el precio sugerido u oferta el precio adecuado para ti.
    fontawesome_icon_name                 : money-bill

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/header.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#121212"

link_color                                : "#ff7701"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ff7701"
feature_text_color                        : "#656565"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
